Make platforms optional
petester42/framework-generate pull request #5
Opened 2017-06-05 15:25 UTC by tbaranes

Close #2 

This PRs allows the user to use only the platforms he's interested in: one, two, three or the four!

2017-06-06 02:54 UTC, pmairoldi requested changes
Aside from the runtime exception looks good. I think we can also change the `settings['TARGETED_DEVICE_FAMILY'] = '1,2,3,4'` to use the platforms specified in the target but that can be done separately.

2017-06-06 02:54 UTC, petester42 commented on lib/framework-generate/target.rb
> +      end
`FrameworkGenerate::Platform::deployment_target` and `FrameworkGenerate::Platform::search_paths` take 2 parameters not one. Maybe you forgot to commit that change?

2017-06-06 06:37 UTC, tbaranes commented on lib/framework-generate/target.rb
> +      end
My bad, it's pushed

2017-06-07 02:14 UTC, pmairoldi approved these changes

2017-06-07 02:32 UTC, merged

2017-06-07 02:57 UTC, petester42 commented
Published a new version (1.1.1) with these fixes. Enjoy!